[2024-07-13T10:34:29.933+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:34:29.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:34:30.015+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:34:30.000+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:34:30.244+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:34:30.192+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 35, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:34:30.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:34:30.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.810 seconds
[2024-07-13T10:35:01.534+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:35:01.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:35:01.538+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:35:01.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:35:01.553+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:35:01.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 35, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:35:01.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:35:01.572+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.042 seconds
[2024-07-13T10:35:31.738+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:35:31.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:35:31.743+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:35:31.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:35:31.762+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:35:31.757+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 35, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:35:31.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:35:31.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.053 seconds
[2024-07-13T10:36:02.567+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:36:02.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:36:02.627+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:36:02.626+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:36:02.687+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:36:02.678+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 35, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:36:02.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:36:02.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.156 seconds
[2024-07-13T10:36:33.010+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:36:33.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:36:33.013+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:36:33.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:36:33.034+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:36:33.031+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 35, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:36:33.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:36:33.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.049 seconds
[2024-07-13T10:37:03.894+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:37:03.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:37:03.897+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:37:03.897+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:37:03.915+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:37:03.912+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 35, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:37:03.916+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:37:03.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.050 seconds
[2024-07-13T10:37:34.434+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:37:34.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:37:34.437+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:37:34.437+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:37:34.456+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:37:34.451+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 35, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:37:34.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:37:34.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.052 seconds
[2024-07-13T10:38:05.501+0000] {processor.py:161} INFO - Started process (PID=440) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:38:05.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:38:05.508+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:38:05.507+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:38:05.535+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:38:05.529+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 35, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:38:05.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:38:05.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.070 seconds
[2024-07-13T10:38:30.724+0000] {processor.py:161} INFO - Started process (PID=500) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:38:30.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:38:30.728+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:38:30.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:38:30.789+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:38:30.782+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 35, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:38:30.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:38:30.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.107 seconds
[2024-07-13T10:39:01.672+0000] {processor.py:161} INFO - Started process (PID=559) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:39:01.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:39:01.675+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:39:01.675+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:39:01.692+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:39:01.688+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 35, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:39:01.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:39:01.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.044 seconds
[2024-07-13T10:39:32.496+0000] {processor.py:161} INFO - Started process (PID=618) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:39:32.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:39:32.502+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:39:32.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:39:32.542+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:39:32.537+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 34, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:39:32.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:39:32.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.081 seconds
[2024-07-13T10:40:03.472+0000] {processor.py:161} INFO - Started process (PID=677) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:40:03.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:40:03.476+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:03.475+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:40:03.507+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:03.500+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 34, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:40:03.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:40:03.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.077 seconds
[2024-07-13T10:40:34.473+0000] {processor.py:161} INFO - Started process (PID=736) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:40:34.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:40:34.478+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:34.477+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:40:34.506+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:34.501+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/deploy_flask_app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/deploy_flask_app.py", line 34, in <module>
    build_image >> run_container >> end
    ~~~~~~~~~~~~^^~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(BashOperator): build_image>, <Task(BashOperator): run_container>]
[2024-07-13T10:40:34.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:40:34.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.067 seconds
[2024-07-13T10:40:48.878+0000] {processor.py:161} INFO - Started process (PID=755) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:40:48.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:40:48.882+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:48.882+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:40:48.910+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:40:49.056+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:49.055+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:deploy_flask_app
[2024-07-13T10:40:49.068+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:49.067+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:deploy_flask_app
[2024-07-13T10:40:49.076+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:49.076+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:deploy_flask_app
[2024-07-13T10:40:49.077+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:49.077+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:40:49.090+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:49.090+0000] {dag.py:3118} INFO - Creating ORM DAG for deploy_flask_app
[2024-07-13T10:40:49.102+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:40:49.102+0000] {dag.py:3954} INFO - Setting next_dagrun for deploy_flask_app to 2023-03-21 00:00:00+00:00, run_after=2023-03-22 00:00:00+00:00
[2024-07-13T10:40:49.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.254 seconds
[2024-07-13T10:41:25.967+0000] {processor.py:161} INFO - Started process (PID=818) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:41:25.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:41:25.987+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:41:25.986+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:41:26.207+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:41:26.378+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:41:26.378+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:41:26.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.991 seconds
[2024-07-13T10:43:05.392+0000] {processor.py:161} INFO - Started process (PID=873) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:43:05.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:43:05.396+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:43:05.395+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:43:05.442+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:43:05.679+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:43:05.678+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:43:06.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 1.276 seconds
[2024-07-13T10:43:37.039+0000] {processor.py:161} INFO - Started process (PID=932) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:43:37.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:43:37.042+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:43:37.041+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:43:37.061+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:43:37.086+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:43:37.086+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:43:37.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.108 seconds
[2024-07-13T10:44:07.257+0000] {processor.py:161} INFO - Started process (PID=991) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:44:07.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:44:07.266+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:44:07.265+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:44:07.302+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:44:07.341+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:44:07.340+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:44:07.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.187 seconds
[2024-07-13T10:44:37.851+0000] {processor.py:161} INFO - Started process (PID=1050) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:44:37.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:44:37.853+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:44:37.853+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:44:37.866+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:44:37.884+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:44:37.883+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:44:37.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.076 seconds
[2024-07-13T10:45:08.187+0000] {processor.py:161} INFO - Started process (PID=1106) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:45:08.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:45:08.189+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:45:08.189+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:45:08.206+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:45:08.227+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:45:08.226+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:45:08.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.089 seconds
[2024-07-13T10:45:38.640+0000] {processor.py:161} INFO - Started process (PID=1164) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:45:38.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:45:38.642+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:45:38.642+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:45:38.656+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:45:38.676+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:45:38.676+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:45:38.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.088 seconds
[2024-07-13T10:46:08.864+0000] {processor.py:161} INFO - Started process (PID=1220) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:46:08.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:46:08.867+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:46:08.867+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:46:08.892+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:46:08.924+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:46:08.923+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:46:08.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.135 seconds
[2024-07-13T10:46:39.046+0000] {processor.py:161} INFO - Started process (PID=1276) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:46:39.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:46:39.048+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:46:39.048+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:46:39.063+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:46:39.081+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:46:39.081+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:46:39.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.083 seconds
[2024-07-13T10:47:09.504+0000] {processor.py:161} INFO - Started process (PID=1335) to work on /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:47:09.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/deploy_flask_app.py for tasks to queue
[2024-07-13T10:47:09.506+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:47:09.505+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:47:09.530+0000] {processor.py:840} INFO - DAG(s) 'deploy_flask_app' retrieved from /opt/airflow/dags/deploy_flask_app.py
[2024-07-13T10:47:09.565+0000] {logging_mixin.py:188} INFO - [2024-07-13T10:47:09.564+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T10:47:09.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/deploy_flask_app.py took 0.166 seconds
